name: park_genie
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.3
dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2  # Updated to the latest version
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.0.13
  flashy_tab_bar2: ^0.0.10
  loading_animation_widget: ^1.3.0
  logger: ^2.4.0
  flutter_secure_storage: ^8.0.0
  carousel_slider: ^5.0.0
  google_fonts: ^5.0.0
  lottie: ^3.2.0
  flutter_logs: ^2.0.2
  image_picker: ^1.1.2
  intl: ^0.18.0 # Use the latest version
  awesome_dialog: ^3.2.1
  dropdown_button2: ^2.3.9
  animated_text_kit: ^4.2.2
  flutter_staggered_animations: ^1.1.1
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  flutter_rating_bar: ^4.0.1
  easy_stepper: ^0.8.5+1
  share_plus: ^9.0.0
  connectivity_plus: ^6.1.3
  sqflite: ^2.4.1
  path_provider: ^2.1.2
  qr_flutter: ^4.1.0
  qr_code_scanner: ^1.0.1
  flutter_screenutil: ^5.9.3
  fl_chart: 0.63.0
  image: ^4.5.3
  flutter_native_splash: ^2.4.5
  blue_thermal_printer: ^1.2.0
  permission_handler: ^11.4.0
  camera: ^0.11.1
  google_mlkit_text_recognition: ^0.1.0
  video_player: ^2.9.3
  network_info_plus: ^4.1.0
  network_tools: ^3.0.1
  animations: ^2.0.7
  esc_pos_utils_plus: ^2.0.4
  material: ^1.0.0+2
  ping_discover_network_forked: ^0.0.1
  flutter_esc_pos_network: ^1.0.3
  usb_serial: ^0.3.0
  package_info_plus: ^4.2.0
  flutter_blue_plus: 1.34.3
  path: any
  android_alarm_manager_plus: ^4.0.7
  flutter_local_notifications: ^19.1.0
  archive: ^4.0.7
  file_picker: ^8.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.3

flutter_native_splash:
  color: "#FCFCFB"  # ← Change this to any HEX color you want
  image: assets/images/park_genie_logo.png  # Path to your splash image
  android: true
  ios: true
  android_12:
    color: "#FCFCFB"  # ← Change this to any HEX color you want
    image: assets/images/park_genie_logo.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon_resized.png"


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/